//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBanking.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountRequest
    {
        public int RequestId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string AadharNo { get; set; }
        public string Occupation { get; set; }
        public string Address { get; set; }
        public string ServiceReferenceNo { get; set; }
        public string Status { get; set; }
        public string RejectionReason { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
        public Nullable<int> ReviewedBy { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
