//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBanking.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiary
    {
        public int BeneficiaryId { get; set; }
        public int CustomerId { get; set; }
        public string BeneficiaryName { get; set; }
        public string BeneficiaryAccountNo { get; set; }
        public string NickName { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
