//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBanking.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public int CustomerId { get; set; }
        public string LoginPasswordHash { get; set; }
        public string TransactionPasswordHash { get; set; }
        public Nullable<int> FailedAttempts { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
